import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {CONTOUR_DEFAULTS,normalizeContour,contourSources,applyContourMaterials} from '../src/contour-settings.js';
test('new defaults and explicit legacy recipes remain distinct through JSON round trips',()=>{assert.equal(normalizeContour().enabled,true);assert.equal(normalizeContour(undefined,true).enabled,false);const custom=normalizeContour({highlightAngle:270,shadowAngle:90,shadow:false,highlightWidth:.42});assert.deepEqual(normalizeContour(JSON.parse(JSON.stringify(custom))),custom);});
test('directions are independent and invalid recipe values cannot poison shader uniforms',()=>{const s=normalizeContour({highlightAngle:NaN,shadowAngle:90,shadowOffset:Infinity,highlightStrength:12,shadowSoftness:-1});assert.equal(s.highlightAngle,CONTOUR_DEFAULTS.highlightAngle);assert.equal(s.shadowAngle,90);assert.equal(s.highlightStrength,1);assert.equal(s.shadowSoftness,.2);assert.ok(Object.values(s).every(v=>typeof v==='boolean'||Number.isFinite(v)));});
test('contour mode suppresses the strip without losing saved lamps or their enabled state',()=>{const sources=[{shape:'strip',enabled:true},{shape:'area',enabled:true},{kind:'dark',enabled:true}];const modified=contourSources(sources,normalizeContour());assert.equal(modified[0].enabled,false);assert.equal(sources[0].enabled,true);assert.equal(modified[1],sources[1]);assert.equal(contourSources(sources,{enabled:false}),sources);});
test('physical shadow flags are applied to tracer materials and restored in legacy mode',()=>{const group=new THREE.Group(),mat=new THREE.MeshPhysicalMaterial();group.add(new THREE.Mesh(new THREE.BoxGeometry(),mat));applyContourMaterials(group,{enabled:true});assert.equal(mat.castShadow,false);applyContourMaterials(group,{enabled:false});assert.equal(mat.castShadow,true);group.children[0].geometry.dispose();mat.dispose();});

import {updateRimHighlight} from '../src/rim-highlight.js';
test('disabled legacy stripe does not upload vertex colours when a lamp moves',()=>{const group=new THREE.Group(),geometry=new THREE.BufferGeometry();geometry.setAttribute('rimProfile',new THREE.Float32BufferAttribute([.4,1,0],3));const mat=new THREE.MeshPhysicalMaterial(),mesh=new THREE.Mesh(geometry,mat);mesh.userData.surface='rim-cap';group.add(mesh);const settings={rimHighlight:0,rimHighlightWidth:.3};assert.equal(updateRimHighlight(group,settings,[{kind:'light',enabled:true,power:1,azimuth:0}]),true);assert.equal(updateRimHighlight(group,settings,[{kind:'light',enabled:true,power:1,azimuth:180}]),false);geometry.dispose();mat.dispose();});
